// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAljVevO4t-U9MkAay6pmGU9zNdZM_fuM',
    appId: '1:163229467121:web:5a65b715cfd0605ed7c450',
    messagingSenderId: '163229467121',
    projectId: 'e-reading-app-auth',
    authDomain: 'e-reading-app-auth.firebaseapp.com',
    storageBucket: 'e-reading-app-auth.appspot.com',
    measurementId: 'G-LPC0L79J3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI7M2n35ruieM_7AOcYbX7m35mbT3IOxg',
    appId: '1:163229467121:android:62ce1262089ff9ccd7c450',
    messagingSenderId: '163229467121',
    projectId: 'e-reading-app-auth',
    storageBucket: 'e-reading-app-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqM9urXbnDIrdhZcrFlBjOImguomhxgOA',
    appId: '1:163229467121:ios:b76d9d4b9a5f7b0ad7c450',
    messagingSenderId: '163229467121',
    projectId: 'e-reading-app-auth',
    storageBucket: 'e-reading-app-auth.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqM9urXbnDIrdhZcrFlBjOImguomhxgOA',
    appId: '1:163229467121:ios:53da07054f8b5bd5d7c450',
    messagingSenderId: '163229467121',
    projectId: 'e-reading-app-auth',
    storageBucket: 'e-reading-app-auth.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
