// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhhqSciVAWUWrCsG3V7AdHKGdqSKOeqtU',
    appId: '1:185940337142:web:c2053970b0e84374f527d7',
    messagingSenderId: '185940337142',
    projectId: 'fir-flutter-auth-33437',
    authDomain: 'fir-flutter-auth-33437.firebaseapp.com',
    storageBucket: 'fir-flutter-auth-33437.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5rLJCkNS8QDVQec3H23oxIccu9R65KI0',
    appId: '1:185940337142:android:6ea6555e3418316ef527d7',
    messagingSenderId: '185940337142',
    projectId: 'fir-flutter-auth-33437',
    storageBucket: 'fir-flutter-auth-33437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg2cLw-WYTZOqoCforsMF4fH3M0x8GFco',
    appId: '1:185940337142:ios:fc57e10edd103e5ef527d7',
    messagingSenderId: '185940337142',
    projectId: 'fir-flutter-auth-33437',
    storageBucket: 'fir-flutter-auth-33437.appspot.com',
    iosBundleId: 'com.example.ebookFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg2cLw-WYTZOqoCforsMF4fH3M0x8GFco',
    appId: '1:185940337142:ios:fc57e10edd103e5ef527d7',
    messagingSenderId: '185940337142',
    projectId: 'fir-flutter-auth-33437',
    storageBucket: 'fir-flutter-auth-33437.appspot.com',
    iosBundleId: 'com.example.ebookFrontend',
  );
}
